/**********************************************************************
* Pulsetrain.c
* Program generates a Pulse train,  generated by FTM3 and output on PTE8
*Created by: Karen Aguilar, Rodrick Muya 03/08/2022
***********************************************************************/
/**********************************************************************
* Include header files
**********************************************************************/
#include "os.h"
#include "app_cfg.h"
#include "MCUType.h"
#include "K65TWR_ClkCfg.h"
#include "LCDLayered.h"
#include "uCOSKey.h"
#include "K65TWR_TSI.h"
#include "MK65F18.h"
#include "SysTickDelay.h"
#include "Pulsetrain.h"
#include "K65TWR_GPIO.h"

typedef struct{
    INT32U pulsefreq;
    INT32U pulseduty;
} PULSE_DATA;
static PULSE_DATA PulseData;
/*****************************************************************************************
* Allocate task control blocks
*****************************************************************************************/
static OS_TCB PulsewaveTaskTCB;
/*****************************************************************************************
* Allocate task stack space.
*****************************************************************************************/
static CPU_STK PulsewaveTaskStk[APP_CFG_PULSE_WAVE_TASK_STK_SIZE];
/*****************************************************************************************
* Mutex Key
*****************************************************************************************/
static OS_MUTEX PulseKey;
/*****************************************************************************************
* Task Function and Function Prototypes.
*****************************************************************************************/
static void PulsewaveTask(void *p_arg);
static INT16U GetPulseFreq(void);
static INT16U GetPulseDuty(void);
/****************************************************************************************
* PulseWaveInit()-Public
* Creates Pulse Wave task
* Created by:Karen Aguilar, Rodrick Muya 03/08/2022
****************************************************************************************/
void PulseWaveInit(void){

    OS_ERR os_err;

    OSMutexCreate(&PulseKey, "Pulse Key", &os_err);   /* Create mutex for pulse*/
    OSTaskCreate(&PulsewaveTaskTCB,                   /* Address of TCB assigned to task */
                 "PulsewaveTask",                     /* Name you want to give the task */
                 PulsewaveTask,                       /* Address of the task itself */
                 (void *) 0,                          /* p_arg is not used so null ptr */
                 APP_CFG_PULSE_WAVE_TASK_PRIO,           /* Priority you assign to the task */
                 &PulsewaveTaskStk[0],                /* Base address of task s stack */
                 (APP_CFG_PULSE_WAVE_TASK_STK_SIZE/10u), /* Watermark limit for stack growth */
                 APP_CFG_PULSE_WAVE_TASK_STK_SIZE,       /* Stack size */
                 0,                                  /* Size of task message queue */
                 0,                                  /* Time quanta for round robin */
                 (void *) 0,                         /* Extension pointer is not used */
                 (OS_OPT_TASK_NONE),                 /* Options */
                 &os_err);                           /* Ptr to error code destination */
}

/***********************************************************************************
 * PulsewaveTask()-Private
 * Generate Pulse Train wave.
 * Created by: Karen Aguilar, Rodrick Muya 03/08/2022
 **********************************************************************************/
static void PulsewaveTask(void *p_arg){
	INT16U pulsefreq;
    INT16U pulsedutycycle;
    INT16U pulsefreqcon = 30000;
    INT16U pulsedutycyclecon = 3000;

    INT32U lowfreqstep=234375;
    INT32U highfreqstep=1875000;

    OS_ERR os_err;
    (void)p_arg;                      /* avoid compiler error */

    SIM->SCGC3 |= SIM_SCGC3_FTM3(1);   /* Enable clock gate for FTM3 */
    SIM->SCGC5 |= SIM_SCGC5_PORTE(1);  /* Enable clock gate for PORTE */
    PORTE->PCR[8] = PORT_PCR_MUX(6);        // Set PCR for FTM output
    //Bus clock, center-aligned, divide by 16 prescaler
    FTM3->SC = FTM_SC_CLKS(1) | FTM_SC_CPWMS(1) |FTM_SC_PS(4);
    //PMW polarity
    FTM3->CONTROLS[3].CnSC = FTM_CnSC_ELSA(0)|FTM_CnSC_ELSB(1);
    //Set Initial signal period to 1000 Hz
    FTM3->MOD = FTM_MOD_MOD(pulsefreqcon);
    //Set Initial signal pulse width to 10% (duty cycle)
    FTM3->CONTROLS[3].CnV = FTM_CnV_VAL(pulsedutycyclecon);

    while(1){

		DB2_TURN_OFF();                                 /* Disables debug bit 2 while waiting */
		OSTimeDly(10,OS_OPT_TIME_PERIODIC,&os_err);     /* Task period = 10ms   */
		DB2_TURN_ON();                                  /* Enables debut bit 2 while ready/running */
		pulsefreq = GetPulseFreq();
		pulsedutycycle= GetPulseDuty();

		if(pulsefreq>=100){
			FTM3->SC = FTM_SC_CLKS(1)|FTM_SC_CPWMS(1)|FTM_SC_PS(4);  //set prescaler to divide by 16
			pulsefreqcon=highfreqstep/pulsefreq;                     //convert frequency to useful value
			pulsedutycyclecon=(pulsefreqcon*pulsedutycycle)/100;     //convert duty cycle to useful valu
		}else{
			FTM3->SC = FTM_SC_CLKS(1)|FTM_SC_CPWMS(1)|FTM_SC_PS(7);  //set prescaler to divide by 128
			pulsefreqcon=lowfreqstep/pulsefreq;                      //convert frequency to useful value
			pulsedutycyclecon=(pulsefreqcon*pulsedutycycle)/100;     //convert duty cycle to useful valu
			}
		//set our converted frequency
		FTM3->MOD = FTM_MOD_MOD(pulsefreqcon);                    //updates output frequency FREQ_in IS DOUBLE on the OUTPUT
		FTM3->CONTROLS[3].CnV = FTM_CnV_VAL(pulsedutycyclecon);   //updates output duty cycle
        }
}
/**********************************************************************************
* SetPulseFreq()-Public Function
* Parameters: 32-bit unsigned integer.
* Sets Pulse Frequency.
* Created by: Karen Aguilar 03/08/2022
************************************************************************************/
void SetPulseFreq(INT32U changefreq){
    OS_ERR os_err;
    OSMutexPend(&PulseKey, 0, OS_OPT_PEND_BLOCKING, (CPU_TS*)0, &os_err );
    PulseData.pulsefreq = changefreq;
    OSMutexPost(&PulseKey,OS_OPT_NONE,&os_err);
}
/**************************************************************************************
* SetPulseDuty()-Public function
* Parameters:duty_cycle
* Sets Pulse duty cycle.
* Created by: Karen Aguilar 03/08/2022
****************************************************************************************/
void SetPulseDuty(INT32U duty_cycle){
    OS_ERR os_err;
    OSMutexPend(&PulseKey, 0, OS_OPT_PEND_BLOCKING, (CPU_TS*)0, &os_err );
    PulseData.pulseduty = duty_cycle;
    OSMutexPost(&PulseKey,OS_OPT_NONE,&os_err);
}
/*****************************************************************************************
* GetPulseFreq()-Private
* Gets the pulse wave frequency in mutex.
* Created by: Karen Aguilar, Rodrick Muya 03/06/2022
*****************************************************************************************/
static INT16U GetPulseFreq(void){
    INT16U returnfreq;
    OS_ERR os_err;
    OSMutexPend(&PulseKey, 0, OS_OPT_PEND_BLOCKING, (CPU_TS*)0, &os_err );
    returnfreq = PulseData.pulsefreq;
    OSMutexPost(&PulseKey,OS_OPT_NONE,&os_err);
    return returnfreq;
}
/*****************************************************************************************
* GetPulseDuty() - Private
* Gets the pulse duty cycle in mutex.
* Created by: Karen Aguilar, Rodrick Muya 03/06/2022
*****************************************************************************************/
static INT16U GetPulseDuty(void){
	INT16U returnduty;
    OS_ERR os_err;
    OSMutexPend(&PulseKey, 0, OS_OPT_PEND_BLOCKING, (CPU_TS*)0, &os_err );
    returnduty = PulseData.pulseduty;
    OSMutexPost(&PulseKey,OS_OPT_NONE,&os_err);
    return returnduty;
}
